title: Harmony Reference
email: info@mobilejazz.com
description: >-
  Harmony concepts and code examples from Mobile Jazz.
baseurl: ""
url: "https://harmony.mobilejazz.com"
twitter_username: mobilejazzcom
github_username: mobilejazz

sass:
  load_paths:
    - node_modules
    - _sass
    - _layouts
    - _includes

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "main/main"

gems:
  - jekyll-relative-links
