version: "3.5"
services:
  harmony-reference:
    image: registry.mobilejazz.com/harmony/documentation:$HARMONY_REFERENCE_VERSION
    environment:
      - VIRTUAL_HOST=harmony.mobilejazz.com
      - LETSENCRYPT_HOST=harmony.mobilejazz.com
      - LETSENCRYPT_EMAIL=harmony@mobilejazz.com
  drone-server:
    image: drone/drone:1.6.4
    env_file:
      - .env-prod
    volumes:
      - /var/lib/drone:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=$DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET=$DRONE_GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=drone-harmony.mobilejazz.com
      - DRONE_SERVER_PROTO=https
      - DRONE_USER_CREATE=username:joselufo,machine:false,admin:true,token:29971c7617c44e9e014474989e18ae73
      - DRONE_TLS_AUTOCERT=false
      - VIRTUAL_HOST=drone-harmony.mobilejazz.com
      - LETSENCRYPT_HOST=drone-harmony.mobilejazz.com
      - LETSENCRYPT_EMAIL=drone.harmony@mobilejazz.com
    ports:
      - '2000:80'
      - '8443:443'
    restart: unless-stopped
  drone-runner-docker:
    image: drone/drone-runner-docker:latest
      - .env-prod
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone-server
    ports:
      - '3000:3000'
    environment:
      - DRONE_RPC_HOST=drone-harmony.mobilejazz.com
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=2
