version: "3.5"
services:
    harmony-reference:
        image: registry.mobilejazz.com/harmony/documentation:$HARMONY_REFERENCE_VERSION
        environment:
            - VIRTUAL_HOST=harmony.mobilejazz.com
            - LETSENCRYPT_HOST=harmony.mobilejazz.com
            - LETSENCRYPT_EMAIL=harmony@mobilejazz.com
