version: "3.5"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./ssl/certs:/etc/nginx/certs:ro
            - ./ssl/dhparam:/etc/nginx/dhparam
            - ./ssl/conf:/etc/nginx/conf.d
            - ./ssl/vhost:/etc/nginx/vhost.d
            - ./ssl/html:/usr/share/nginx/html
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: unless-stopped
        volumes:
            - ./ssl/certs:/etc/nginx/certs
            - ./ssl/conf:/etc/nginx/conf.d
            - ./ssl/vhost:/etc/nginx/vhost.d
            - ./ssl/html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
